### ISSUE TITLE
mkfold location

### ISSUE THREAD

**Issue by ghost** [renebidart/breakHis#1]
Hi,
Thanks for the code. 
Where is mkfold created in:
`in_loc = os.path.join(base_data_dir, 'mkfold')`
Is there another script that needs to be run before running https://github.com/renebidart/breakHis/blob/master/notebooks/final/make_data.ipynb? 

Also, this folder:
`base_data_dir = '/Users/rb/Documents/waterloo/projects/breakHis/'`
is the same as this folder? 
`loc = '/Users/rb/Documents/waterloo/projects/breakHis/BreaKHis_v1'`

Thanks

**Comment by renebidart** [comment]
The mkfold dataset is created using a script included when you download the dataset. And yes, those should be the same.
