### ISSUE TITLE
ft_pre_model function

### ISSUE THREAD

**Issue by Zvikush90** [renebidart/breakHis#2]
Hi,

I am trying to run the cnn-fine-tuning notebook.
I am getting the following error related to ft_pre_model.

Where is ft_pre_model implemented? Is it a part keras or scipy?
```

NameError                                 Traceback (most recent call last)
<ipython-input-3-9dfcf3cc08be> in <module>()
      5 magnification = 100
      6 
----> 7 ft_pre_model(base_model, data_loc, out_loc, magnification, num_out, epochs_first=5, 
      8                           img_dim=512, layer_train=249)

NameError: name 'ft_pre_model' is not defined
```

**Comment by renebidart** [comment]
I had accidentally deleted them, but I just updated it in models.py. It is just a function to fine tune a Keras model.

**Comment by Zvikush90** [comment]
Awesome!!

**Comment by Zvikush90** [comment]
Awesome!!
