### ISSUE TITLE
models on VGG features

### ISSUE THREAD

**Issue by himanshu2612** [renebidart/breakHis#3]
`classes=8
all_features = np.zeros((num_samples, 4096+classes))`

[https://github.com/renebidart/breakHis/blob/master/notebooks/.ipynb_checkpoints/feature_extraction-checkpoint.ipynb](url)
What  is 4096 here?

**Comment by renebidart** [comment]
Its the number of features in the second last layer of VGG 16

**Comment by himanshu2612** [comment]
Thanks. Got it.
